### ISSUE TITLE
Conditional expressions not wrapped

### ISSUE THREAD

**Issue by donaldzhu** [fusepilot/babel-preset-extendscript#15]
Contrary to what's described in the README, conditional expressions (i.e. chained ternary operations) are not wrapped in brackets, leading to `Expected: :` error.

**Comment by Klustre** [comment]
Do you have a snippet to reproduce this issue?

**Comment by donaldzhu** [comment]
Upon further investigation, it works fine in the CLI. it seems to be a downstream problem with the [extender](https://github.com/Klustre/extender) package I am using, where it somehow doesn't wrap the chained ternary expression when transpiling. Not sure why since I have the same version of this preset and babel installed.

**Comment by Klustre** [comment]
Can you post the ternary you're writing?

**Comment by Klustre** [comment]
Can you post the ternary you wrote?

**Comment by donaldzhu** [comment]
I have been trying to figure out the problem but haven't found the solution yet. The relevant test ternary statement is `const a = false ? false ? 1 : 2 : 3`. After esbuild-plugin-babel's `onLoad` is called and the content is transformed, I log the results in the `onLoad` callback and get `var a = false ? (false ? 1 : 2) : 3;` for that line—which is good. I also double checked with `babel.transform` to make sure the extendscript preset works well.
But when I check the final esbuild output file, the brackets disappeared. I am somewhat aware that the plugins for esbuild aren't the last line of bundling process, so it probably modified the babel output and removed the brackets. I am not too familiar with what goes on in esbuild between calling the plugins and writing to output, but it would be helpful if you might know the answer.

**Comment by Klustre** [comment]
Thanks for the details @donaldzhu. I've [opened an issue](https://github.com/Klustre/extender/issues/6) for `extender`. If you have any more info, please post it there.
